project:
  type: book
  output-dir: docs

book:
  title: "Quarto-uitleg"
  author: 
    - name: "Jolien ten Velden"
      affiliation: "GGD Hart voor Brabant"
    - name: "Pieter Seinen"
    
  chapters:
    - index.qmd
    
    - part: Technieken.qmd
      chapters:
        - Quarto.qmd
        - YAML.qmd
        - Markdown.qmd
        - Codeblokken.qmd
        - HTML.qmd
        - R.qmd
    
    - Digitoegankelijkheid.qmd
    
    - part: "Code snippets.qmd"
      chapters:
        - Icoon_met_tekst.qmd
        - Bol_met_cijfer.qmd
        - Lijngrafiek.qmd
        - Staafgrafiek.qmd
        - Leaflet.qmd
        - Tabellen.qmd
        - Cirkeldiagram.qmd
        - Radarchart.qmd
    


bibliography: references.bib


format:
  html:
    theme: cosmo



