---
number-depth: 0
---


# Introductie {.unnumbered}

R Quarto is een functionaliteit binnen RStudio die het mogelijk maakt om de opmaak van een tekst (denk aan Word) te combineren met code. De code kan geschreven zijn in R, maar andere talen zoals Python, SQL en css zijn ook mogelijk. De output kan worden getoond in verschillende formaten, zoals html, PDF, Word, Powerpoint en ePub. De uitleg  in dit boek zal zich beperken tot html outputs. 

De insteek van dit boek is om uitleg te geven over hoe Quarto gebruikt kan worden om informatieproducten (denk thematische schetsen, tabellenboeken) te maken die voldoen aan de eisen van digitoegankelijkheid. Het eerste deel bestaat uit uitleg over technieken, zoals Quarto zelf, Markdown, html en css. Het tweede deel bestaat uit stukjes voorbeeldcode die al geschreven zijn voor reeds gemaakte thematische schetsen ed, en die makkelijk gekopieerd - en daarna aangepast - kunnen worden voor een nieuw te maken schets.

Je kunt op 2 manieren navigeren in dit boek. Via de linkerkant van de pagina kun je direct naar bepaalde hoofdstukken en secties springen door ze aan te klikken. Je kunt op een pagina zelf ook onderaan naar de vorige of volgende pagina gaan door op de linker- of rechterpijl en bijbehorende titel te klikken. Mocht je navigeren via de balk aan de linkerzijkant, let dan op dat je niet alleen de sub-hoofdstukken aanklikt, maar ook het bovenliggende hoofdstuk (zoals het hoofdstuk "Technieken").
